POST http://localhost:3000/signup
Content-Type: application/x-www-form-urlencoded

username=Joe
&password=123456
&confirmPassword=123456
&url=/joe
&siteName=joe's site

###
POST http://localhost:3000/login
Content-Type: application/x-www-form-urlencoded

username=Joe
&password=123456

###
POST https://cms-societies.herokuapp.com/login
Content-Type: application/json

{"username": "Joe", "password": "123456"}

###

GET https://cms-societies.herokuapp.com/admin/joes-site
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZSIsInVzZXJJZCI6IjYyM2EwZjYwNzMyYjI2M2UzMDg0NmQ0YiIsImlhdCI6MTY0ODU3MzI2NywiZXhwIjoxNjQ4NTc2ODY3fQ.mKzPKgkJsaHYaUW4DnU3uvY6nQW_RwaMkmtLkqlIzDI

###
GET http://localhost:3000/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZSIsInVzZXJJZCI6IjYyM2EwZjYwNzMyYjI2M2UzMDg0NmQ0YiIsImlhdCI6MTY0ODY4NDc2MSwiZXhwIjoxNjQ4Njg4MzYxfQ.1EZvwO7drdimi_xg6p3TaZdp1hcQxdQI16Lr6PtVPOg

###
GET http://localhost:3000/admin/joes-site
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZSIsInVzZXJJZCI6IjYyM2EwZjYwNzMyYjI2M2UzMDg0NmQ0YiIsImlhdCI6MTY0ODY4NDc2MSwiZXhwIjoxNjQ4Njg4MzYxfQ.1EZvwO7drdimi_xg6p3TaZdp1hcQxdQI16Lr6PtVPOg

###
PUT http://localhost:3000/admin/joes-site
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZSIsInVzZXJJZCI6IjYyM2EwZjYwNzMyYjI2M2UzMDg0NmQ0YiIsImlhdCI6MTY0ODY4NTk2MiwiZXhwIjoxNjQ4Njg5NTYyfQ.jIYOB3JlxU93v5Dor5Ih9btM20IALZPlp-d3APjlvZU

{ "name": "Joes Site Home", "contentTemplates": [{"content":"Testing"},{"content":"More testing"}]}

###
POST http://localhost:3000/admin/joes-site
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZSIsInVzZXJJZCI6IjYyM2EwZjYwNzMyYjI2M2UzMDg0NmQ0YiIsImlhdCI6MTY0ODY4NTk2MiwiZXhwIjoxNjQ4Njg5NTYyfQ.jIYOB3JlxU93v5Dor5Ih9btM20IALZPlp-d3APjlvZU

{ "name": "Joes Site Home" }

###
POST https://cms-societies.herokuapp.com/admin/joes-site/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZSIsInVzZXJJZCI6IjYyM2EwZjYwNzMyYjI2M2UzMDg0NmQ0YiIsImlhdCI6MTY0ODc0Mjc0MCwiZXhwIjoxNjQ4NzQ2MzQwfQ.KttEuwRV4IrIFeamX5YuwQ0Whpon1DjtMDK3LE8hygM

{ "name":"Reviews Page", "contentTemplates":[{}]}

###
GET https://cms-societies.herokuapp.com/live/joes-site/reviews

###
GET http://localhost:3000/admin/joes-site/reviews
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZSIsInVzZXJJZCI6IjYyM2EwZjYwNzMyYjI2M2UzMDg0NmQ0YiIsImlhdCI6MTY0ODc0NDA5OSwiZXhwIjoxNjQ4NzQ3Njk5fQ.okhOnkeXiJrkFlI256VGDe5csjJfzbzBWGsTu2Or9rA