POST http://localhost:3000/signup
Content-Type: application/x-www-form-urlencoded

username=Joe
&password=123456
&confirmPassword=123456
&url=/joe
&siteName=joe's site

###
POST http://localhost:3000/login
Content-Type: application/x-www-form-urlencoded

username=Joe
&password=123456

###
POST https://cms-societies.herokuapp.com/login
Content-Type: application/x-www-form-urlencoded

username=Joe
&password=123456

###
GET https://